"""A sealed assessment, and the readings it rests on (DECISIONS.md section 208)."""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, Index, Integer, String
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.enums import Provider, ScanStatus, TaskOutcome
from app.models.base import Base, StrEnumType, TenantOwned


class AuditPackage(TenantOwned, Base):
    """One assessment of one or more frameworks, as it stood when it was sealed.

    The opposite of a report, on purpose. ``compliance.build_export`` is
    generated on request and never stored, because a stored assessment outlives
    the evidence behind it and then there are five copies and a question about
    which is current. An auditor needs exactly the thing that argument rules
    out -- a fixed record of a date -- so a package is named, dated, and never
    updated: it does not claim to be current, and nothing refreshes it.

    ``manifest_sha256`` is taken over the canonical manifest built from this row
    and its items (``compliance.package``), so editing either afterwards is
    detectable by rebuilding it. The ids are generated by the caller, not the
    database, because the manifest names the package and is hashed before the
    row is written.
    """

    __tablename__ = "audit_packages"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    framework_ids: Mapped[list[str]] = mapped_column(ARRAY(String), nullable=False)
    # The catalogue's header for each framework as sealed: a framework's name
    # and version can change after an audit, and the package must still say
    # which one it assessed.
    frameworks: Mapped[list] = mapped_column(JSONB, nullable=False)
    # Every control's verdict and the rules behind it, minus what changes with
    # time (age, whether a payload is still stored): those are answered live.
    controls: Mapped[list] = mapped_column(JSONB, nullable=False)
    # No foreign key: scans are pruned and deleted, and the package outlives them.
    scan_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False)
    # PARTIAL matters most here -- an assessment with a hole in it must say so.
    scan_status: Mapped[ScanStatus] = mapped_column(StrEnumType(ScanStatus, 16), nullable=False)
    scan_completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # The audit period the customer declared. Informational in this version: the
    # evidence is the closing scan's, and the package does not claim more.
    period_start: Mapped[date | None] = mapped_column(Date)
    period_end: Mapped[date | None] = mapped_column(Date)
    manifest_version: Mapped[int] = mapped_column(Integer, nullable=False)
    manifest_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    sealed_by: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), nullable=False)
    sealed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class AuditPackageItem(TenantOwned, Base):
    """One reading a package's controls rest on.

    Copies what ``Evidence`` holds rather than pointing at it, for the reason
    ``FindingEvidence`` does: the scan that took the reading can be deleted, and
    a record of what was read must outlive the thing it was read by. The hash
    names an ``EvidenceBlob`` without a foreign key, and retention keeps every
    blob an item names (``services.retention.prune_blobs``).
    """

    __tablename__ = "audit_package_items"
    __table_args__ = (
        Index(
            "uq_audit_package_items_reading",
            "package_id",
            "evidence_key",
            "cloud_account_id",
            "region",
            unique=True,
            postgresql_nulls_not_distinct=True,
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    package_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("audit_packages.id", ondelete="CASCADE"), nullable=False
    )
    evidence_key: Mapped[str] = mapped_column(String(64), nullable=False)
    # NULL is the tenant directory, as on ``Evidence``.
    cloud_account_id: Mapped[uuid.UUID | None] = mapped_column(PGUUID(as_uuid=True))
    region: Mapped[str | None] = mapped_column(String(32))
    provider: Mapped[Provider] = mapped_column(StrEnumType(Provider, 16), nullable=False)
    outcome: Mapped[TaskOutcome] = mapped_column(StrEnumType(TaskOutcome, 16), nullable=False)
    item_count: Mapped[int] = mapped_column(Integer, nullable=False)
    collected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source_scan_id: Mapped[uuid.UUID | None] = mapped_column(PGUUID(as_uuid=True))
    permissions: Mapped[list] = mapped_column(JSONB, nullable=False)
    endpoints: Mapped[list] = mapped_column(JSONB, nullable=False)
    # NULL where the reading produced nothing: a failed collection is still a
    # cited reading, and a hash of nothing would say otherwise.
    content_hash: Mapped[str | None] = mapped_column(String(64))
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
