"""What only one provider has a word for.

``cloud_connections`` and ``cloud_accounts`` carry a neutral pair -- the trust
boundary and the unit a scan reads -- under Azure's names for them, and that
pair is enough for Azure because everything else about an Azure connection is
already a column: the service principal object id, the consent status, the
scope path.

AWS needs two things Azure has no equivalent of. The scanner role's ARN, which
is what ``sts:AssumeRole`` is called against, and the **external id** that role's
trust policy must require -- per connection, generated by CloudGuard, and the
only thing standing between a third-party scanner and the confused deputy
(MULTI_CLOUD.md section 5). Neither is read by anything neutral, so neither
earns a column.

Holds no customer secret and must not start to. The external id is a name the
customer's own trust policy pins against, not a credential to their
environment; ``cloud_account.py`` records that CloudGuard stores nothing that
could leak access to a customer's cloud, and this is the obvious column in
which to lose that property.

``ConnectionScope`` also gains AWS's three levels in the same change --
ORGANIZATION, ORGANIZATIONAL_UNIT, ACCOUNT. Stored as text, so no type change
is needed here; the column is already wide enough for the longest of them.

Revision ID: 0034
Revises: 0033
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for table in ("cloud_connections", "cloud_accounts"):
        op.execute(
            f"ALTER TABLE {table} "
            "ADD COLUMN provider_ref jsonb NOT NULL DEFAULT '{}'::jsonb;"
        )


def downgrade() -> None:
    for table in ("cloud_connections", "cloud_accounts"):
        op.execute(f"ALTER TABLE {table} DROP COLUMN provider_ref;")
