"""Generate comprehensive Security Rule Catalog for CloudGuard.

Introspects the live rule registry (app.rules.registry.RULE_REGISTRY) to produce
an authoritative, synchronized Markdown catalog in docs/RULE_CATALOG.md.

Usage:
    python apps/api/scripts/generate_rule_catalog.py
    python apps/api/scripts/generate_rule_catalog.py --check
"""

from __future__ import annotations

import argparse
import difflib
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

# Ensure test mode for configuration if unset
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("SUPABASE_JWT_SECRET", "doc-gen-secret")
os.environ.setdefault(
    "DATABASE_URL", "postgresql+asyncpg://cloudguard_app:x@localhost:5432/cg"
)
os.environ.setdefault(
    "DATABASE_OWNER_URL", "postgresql+asyncpg://cloudguard:x@localhost:5432/cg"
)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CATALOG_OUTPUT = REPO_ROOT / "docs" / "RULE_CATALOG.md"


def get_rules() -> list[Any]:
    """Import and return the registered security rules."""
    api_dir = REPO_ROOT / "apps" / "api"
    if str(api_dir) not in sys.path:
        sys.path.insert(0, str(api_dir))

    from app.rules.registry import RULE_REGISTRY

    # Sort deterministically by provider, category, and rule_id
    return sorted(
        RULE_REGISTRY,
        key=lambda r: (
            str(getattr(r, "provider", "")),
            str(getattr(r, "category", "")),
            str(getattr(r, "rule_id", "")),
        ),
    )


def format_compliance(mappings: dict[str, list[str]]) -> str:
    if not mappings:
        return "-"
    parts = []
    for framework, controls in sorted(mappings.items()):
        controls_str = ", ".join(controls[:3])
        if len(controls) > 3:
            controls_str += f" (+{len(controls) - 3})"
        parts.append(f"`{framework}: {controls_str}`")
    return "<br>".join(parts)


def format_applies_to(applies_to: list[Any]) -> str:
    if not applies_to:
        return "Aggregate (Tenant-wide)"
    items = [item.value if hasattr(item, "value") else str(item) for item in applies_to]
    return ", ".join(f"`{i}`" for i in items)


def is_azure(r: Any) -> bool:
    prov = str(getattr(r, "provider", "")).lower()
    return "azure" in prov


def build_markdown_catalog(rules: list[Any]) -> str:
    azure_rules = [r for r in rules if is_azure(r)]
    aws_rules = [r for r in rules if not is_azure(r)]

    total_count = len(rules)
    azure_count = len(azure_rules)
    aws_count = len(aws_rules)

    def count_by_severity(rule_list: list[Any]) -> dict[str, int]:
        counts: dict[str, int] = defaultdict(int)
        for r in rule_list:
            sev = getattr(r.severity, "value", str(r.severity)).upper()
            counts[sev] += 1
        return counts

    az_sev = count_by_severity(azure_rules)
    aws_sev = count_by_severity(aws_rules)

    az_row = (
        f"| **Azure** | 🟢 Active / Live Verified | {az_sev['CRITICAL']} | "
        f"{az_sev['HIGH']} | {az_sev['MEDIUM']} | {az_sev['LOW']} | {azure_count} |"
    )
    aws_row = (
        f"| **AWS** | 🟡 Preview / Offline Tested | {aws_sev['CRITICAL']} | "
        f"{aws_sev['HIGH']} | {aws_sev['MEDIUM']} | {aws_sev['LOW']} | {aws_count} |"
    )

    lines: list[str] = [
        "# CloudGuard — Security Rule Catalog",
        "",
        "> **Auto-generated documentation** from `app/rules/registry.py`.",
        "> Do not edit this file directly; update the rule implementations and run:",
        "> `python apps/api/scripts/generate_rule_catalog.py`",
        "",
        "---",
        "",
        "## Summary & Status",
        "",
        "Deterministic security evaluations against normalized cloud resources.",
        "",
        f"- **Total Registered Rules**: {total_count}",
        f"- **Azure Rules (Active / Production Verified)**: {azure_count}",
        f"- **AWS Rules (Preview / Unverified on Live Accounts)**: {aws_count}",
        "",
        "| Provider | Status | Critical | High | Medium | Low | Total |",
        "|---|---|---|---|---|---|---|",
        az_row,
        aws_row,
        "",
        "> [!IMPORTANT]",
        "> **AWS Rules Status**: The 40+ AWS rules are fully implemented and verified against",
        "> recorded payload fixtures, but have **never been executed against a live AWS account**.",
        "> They remain behind the `AWS_ENABLED` seam until live verification passes",
        "> (see [`docs/AWS_INTEGRATION.md`](AWS_INTEGRATION.md)).",
        "",
        "---",
        "",
        "## Exploitability Scale Reference",
        "",
        "Every rule defines an integer exploitability rating ($0-5$) representing what an attacker",
        "must possess to exploit the worst-case instance:",
        "",
        "- **5 — Internet Unauthenticated**: Reachable from the internet with zero credentials.",
        "- **4 — Guessable / Phishable**: Exploitable with phished/sprayed credentials or IDs.",
        "- **3 — Authenticated**: Requires valid user/service credentials or tenant access.",
        "- **2 — Elevated Foothold**: Requires foothold plus specific role or network elevation.",
        "- **1 — Weakened Defense in Depth**: Impairs telemetry, audit, or defense-in-depth.",
        "- **0 — Non-exploitable**: Informational hygiene / compliance with no direct attack path.",
        "",
        "---",
        "",
        "## Master Rule Index",
        "",
        "| Rule ID | Name | Provider | Category | Severity | Exploitability | Target Scope |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in rules:
        provider_name = "Azure" if is_azure(r) else "AWS"
        sev_val = getattr(r.severity, "value", str(r.severity)).upper()
        scope_str = format_applies_to(r.applies_to)
        row = (
            f"| [{r.rule_id}](#{r.rule_id.lower()}) | {r.name} | {provider_name} | "
            f"{r.category} | {sev_val} | {r.exploitability} | {scope_str} |"
        )
        lines.append(row)

    lines.extend([
        "",
        "---",
        "",
        "## Rule Details by Provider",
        "",
    ])

    def render_provider_rules(
        provider_title: str, rule_list: list[Any], is_aws: bool = False
    ) -> None:
        lines.extend([
            f"### {provider_title}",
            "",
        ])
        if is_aws:
            lines.extend([
                "> ⚠️ **Notice**: These rules are part of the AWS preview connector and have",
                "> been validated against offline fixtures only.",
                "",
            ])

        by_category: dict[str, list[Any]] = defaultdict(list)
        for r in rule_list:
            by_category[r.category].append(r)

        for cat in sorted(by_category.keys()):
            cat_rules = by_category[cat]
            lines.extend([
                f"#### {cat} ({len(cat_rules)} rules)",
                "",
            ])
            for r in cat_rules:
                sev_val = getattr(r.severity, "value", str(r.severity)).upper()
                effort = f"~{r.estimated_effort_minutes} min"
                scope_name = getattr(r.scope, "value", str(r.scope))
                lines.extend([
                    f"##### <a id=\"{r.rule_id.lower()}\"></a>`{r.rule_id}` — {r.name}",
                    "",
                    f"- **Severity**: `{sev_val}` | **Exploitability**: `{r.exploitability}/5` | "
                    f"**Effort**: `{effort}`",
                    f"- **Scope**: `{scope_name}`",
                    f"- **Applies to**: {format_applies_to(r.applies_to)}",
                ])

                if r.compliance_mappings:
                    comp_items = [
                        f"`{k}: {', '.join(v)}`" for k, v in sorted(r.compliance_mappings.items())
                    ]
                    lines.append(f"- **Compliance Mappings**: {' &bull; '.join(comp_items)}")

                if r.description:
                    lines.extend(["", f"**Description**: {r.description.strip()}"])

                if r.rationale:
                    lines.extend(["", f"**Rationale**: {r.rationale.strip()}"])

                if r.remediation:
                    lines.extend([
                        "",
                        "**Remediation**:",
                        "```bash",
                        r.remediation.strip(),
                        "```",
                    ])
                lines.append("")

    render_provider_rules("Azure Rules", azure_rules, is_aws=False)
    render_provider_rules("AWS Rules (Preview)", aws_rules, is_aws=True)

    return "\n".join(lines).strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or check Security Rule Catalog documentation."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if docs/RULE_CATALOG.md is up-to-date without overwriting.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_CATALOG_OUTPUT,
        help="Target path for RULE_CATALOG.md",
    )

    args = parser.parse_args()

    rules = get_rules()
    new_markdown = build_markdown_catalog(rules)
    target = args.output

    if args.check:
        if not target.exists():
            print(f"Error: {target} does not exist. Run without --check to generate.")
            return 1

        existing_markdown = target.read_text(encoding="utf-8")
        if existing_markdown != new_markdown:
            print(f"Error: {target} is out of date. Diff:")
            diff = difflib.unified_diff(
                existing_markdown.splitlines(),
                new_markdown.splitlines(),
                fromfile="committed RULE_CATALOG.md",
                tofile="generated RULE_CATALOG.md",
                lineterm="",
            )
            for line in list(diff)[:50]:
                print(line)
            print("\nRun `python apps/api/scripts/generate_rule_catalog.py` to regenerate.")
            return 1

        print(f"OK: {target} matches current RULE_REGISTRY.")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(new_markdown, encoding="utf-8")
    print(f"Wrote {len(rules)} rules to {target} ({len(new_markdown.encode('utf-8'))} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
